# ========== CONFIGURAÇÃO GERAL ==========
title: "SMARTWAY NPS"
description: "Plataforma de pesquisas NPS hospedada no GitHub Pages"

# publicação em raiz do domínio
baseurl: ""      # não há sub-diretório
url: "https://comercialsw.github.io"

# ========== MARKDOWN ==========
markdown: kramdown
kramdown:
  input: GFM

# ========== PERMALINKS BONITOS ==========
permalink: /:title/

# ========== PLUGINS ==========
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ========== TEMA ==========
theme: jekyll-theme-cayman

# ========== OPÇÕES EXTRA ==========
exclude:
  - node_modules
  - vendor
lsi: false
incremental: false

# ========== STATICMAN ==========
# Esta chave é lida dentro do HTML via {{ site.staticman_url }}
staticman_url: "https://api.staticman.net/v3/entry/github/comercialsw/nps/main/comments"
